import random
import time
Loop = 1
End = False
while True:
    if End == True:
        Stop = input("Do you want to quit? y/n: ")
        if Stop =='y':
            quit("Bye")
    name = input("What is your name: ")
    print("You wake up in a cavern without memory of how you got there")
    time.sleep(1)
    print("")
    print("You see several structures in front of you")
    time.sleep(1)
    print("")
    choice1 = input("Do you investigate the structures? y/n: ")

    if choice1 =='y':
        print("")
        time.sleep(1)
        print("You walk towards the structures")
        print("")
        time.sleep(1)
        print("You are infront of the nearest structure")
        print("")
        time.sleep(1)
        print("You see something that looks like a door")
        print("")
        time.sleep(1)
        path2 = input("Do you want to open the door? y/n: ")
        if path2 =='y':
            print("")
            time.sleep(1)
            print("You open the door")
            print("")
            time.sleep(1)
            print("Inside the structure you see a bloody huge hole in the ground")
            print("")
            time.sleep(1)
    if choice1 =='n':
        print("")
        time.sleep(1)
        print("You decide to stay away from the structures")
        print("")
        time.sleep(1)
        print("Do you want to look around the cavern?")
        print("")
        time.sleep(1)
        path1 = input("y/n: ")
        if path1 =='y':
            print("")
            time.sleep(1)
            print("You look around the cavern")
            print("")
            time.sleep(1)
            print("You find a tunnel to the left of the structures")
        if path1 =='n':
            print("")
            time.sleep(1)
            print("You gain the paranoid trait")
            print("")
            time.sleep(1)
            print("You decide to stay where you are")
            print("")
            time.sleep(1)
            print("Do you want to look around your safe space?")
            print("")
            Paranoid = input("y/n: ")
            if Paranoid =='y':
                time.sleep(1)
                print("You look around your safe space")
                print("")
                time.sleep(1)
                print("You find a carrot")
                time.sleep(1)
                print("")
                print("Do you want to look around the cavern now?")
                print("")
                time.sleep(1)
                Paranoid1 = input("y/n: ")
                if Paranoid1 =='y':
                    print("You lose the trait paranoid")
                    print("")
                    time.sleep(1)
                    print("You look around the cavern")
                    print("")
                    time.sleep(1)
                    print("You see a tunnel to the left of the structures")
                if Paranoid1 =='n':
                    print("You just sit in your safe space eating carrots")
                    print("")
                    time.sleep(2)
                    print("Do you want to explore now?")
                    Paranoid2 = input("y/n: ")
                    if Paranoid2=='y':
                        print("")
                        print("You lose the paranoid trait")
                        print("")
                        time.sleep(1)
                        print("You look around the cavern")
                        print("")
                        time.sleep(1)
                        print("You see a tunnel a bit to the left of the structures")
                        print("")
                        time.sleep(1)
                        print("Do you want to explore the tunnel?")
                        Tunnel = input("y/n: ")
                        if Tunnel =='y':
                            print("")
                            time.sleep(1)
                            print("You walk toward the tunnel avoiding the structures as much as you can")
                            print("")
                            time.sleep(1)
                            print("You go into the tunnel")
                            time.sleep(1)
                        if Tunnel =='n':
                            print("")
                            time.sleep(1)
                            print("You decide that you want to keep looking around instead")
                            print("")
                            time.sleep(1)
                            print("You find a giant pile of carrots")
                            print("")
                            time.sleep(1)
                            print("Do you want to eat all of them?")
                            Carrot = input("y/n: ")
                            if Carrot =='y':
                                print("")
                                time.sleep(2)
                                print("You get poisoned because you ate random poisoned carrots in a cave")
                                print("")
                                time.sleep(1)
                                print("Do you want to look in the structures for some kind of cure?")
                                Poison = input("y/n: ")
                                if Poison =='y':
                                    print("")
                                    time.sleep(1)
                                    print("You sprint towards the structures to try and find medecine")
                                    print("")
                                    time.sleep(1)
                                    print("You see a red cross on one of the structures")
                                    print("")
                                    time.sleep(1)
                                    print("Do You want to investigate the structure")
                                    Hospital = input("y/n: ")
                                    if Hospital =='y':
                                        print("")
                                        time.sleep(1)
                                        print("You run up to the door and open it")
                                    if Hospital =='n':
                                        print("")
                                        time.sleep(1)
                                        print("You have made a massive misstake")
                                        print("")
                                        time.sleep(1)
                                        print("You ignore the building with the medicine and run around untill you die")
                                        print("")
                                        time.sleep(1)
                                        print(name,"dies from poisoned carrots")
                                        End = True
                                        print("-------------------------------")
                    if Paranoid2=='n':
                        print("")
                        print("You absolutly cannot move from your safe space and stay there forever")
                        print("")
                        time.sleep(2)
                        print("Eventually you die by starvation")
                        print("")
                        time.sleep(1)
                        print(name,"lost")
                        print("----------------------------------------")
                        End = True
            if Paranoid =='n':
                print("You gain the insane trait")
                print("")
                time.sleep(2)
                print("Because you are insane you lose track of time and die of starvation")
                print("")
                time.sleep(1)
                print("Crazy Bastard")
                print("")
                time.sleep(2)
                print("---------------------------------------")
                End = True
            
